### ISSUE TITLE
API.wallBack causes the program to lock

### ISSUE THREAD

**Issue by Nimolas** [mackorone/mms-python#4]
I recently tried using this API wrapped on top of the mms application you created, and it seems that when you call `API.wallBack()` the program locks up and stop executing the provided python code.

I'm using the Feburary 2022 version

with the following example:

```python
log("calling wallFront")
API.wallFront()
log("called wallFront")

log("calling wallLeft")
API.wallLeft()
log("called wallLeft")

log("calling wallRight")
API.wallRight()
log("called wallRight")

log("calling wallBack")
API.wallBack()
log("called wallBack")

log("Complete")
```

You can see this result:

![image](https://github.com/mackorone/mms-python/assets/38698304/79f421dd-d47a-42d6-b74b-ad1a1b01829a)

I couldn't see a way to see the logs for the application to see what it was doing.

Is there something I'm missing or doing incorrectly?

**Comment by mackorone** [comment]
Thanks for reporting.

The lockup is happening because the Python API was updated to include the `wallBack` method but the most recent release of the simulator doesn't support it yet. I hope to upload a new release soon, but until then, you can either:
1. Avoid calling `wallBack`
2. Build and run the simulator from source code (rather than downloading the latest release)

**Comment by mackorone** [comment]
@Nimolas a [new version](https://github.com/mackorone/mms/releases/tag/v1.2.0) of the simulator is now available! The wall-checking commands should all work as expected in the new version. Please reopen this issue if they don't.
